### PR TITLE
Updates for v14.2

### PR DESCRIPTION
**Pull request by Dude4Linux**
I hope I remembered all the steps to prepare for the new release.

### CODE REVIEW

**Comment by JedMeister** [comment]
Thanks tons John. I'll have a proper look over this really soon. As you've no doubt seen, I've opened an issue on the tracker to ensure it doesn't get missed.

**Comment by JedMeister** [comment]
Hey @Dude4Linux should this be good to go now? Or would you prefer me to hold off?

Also I'm guessing that you probably meant to make this pull request against the [TurnKey repo](https://github.com/turnkeylinux-apps/ansible)?

**Comment by Dude4Linux** [comment]
Hi @JedMeister I've been testing the 14.2 ansible against the proposed 14.2 LXC appliance. Still struggling with some issues related to Webmin and the new ansible and also dns name resolution on LXC. The testing has turned up an issue with the init.yml on ansible (now fixed) but more may be forthcoming. I thought I had pinned down the Webmin problem to the stunnel prematurely closing the connection, but now I'm not so sure because failures continue.
The scenario I'm seeing is that when I create a container using an ansible playbook, the container is created and started on the LXC host. When the container starts, it gets an IP address from dhcp (dnsmasq), but does not immediately appear in dns (also dnsmasq). There appears to be a delay of a several seconds before the container name can be resolved. More puzzlingly, I've seen cases where even after the host command returns the proper IP address of the container, using curl on the same name fails to resolve. I presume this is one of the causes of the ansible playbook failing.  
The ansiible playbook in question first creates and configures a container, then runs some tests including logging into Webmin on port 12321, and if the tests pass it then shuts down and destroys the container. I'm working on the theory that the problem is caused by repeated runs using the same container name, and that it has something to do with the dns cache on LXC.
Test procedure:
1. Remove all containers on LXC
2. Clear the dns cache by restarting dnsmasq
3. Create and start a container
4. Verify that name resolution is working
5. Verify that ansible can test Webmin login
6. Stop and destroy the container
7. Create and start a new container with the same name but different MAC address
8. Verify that name resolution is working
9. Test if ansible can access Webmin login
10. Did it pass?

At this point I'm not sure if the problem is caused by LXC/dnsmasq, my ansible playbooks, or the new version of ansible. If you could hold off for a week or so without delaying the 14.2 release it would give me time to work the issue. In any case, the LXC appliance will need some changing.

And yes, I did mean to issue the pull request against the TurnKey repo.  My setup has been wacked since I created the original appliance here.  I guess I need to completely delete my repo and fork the TurnKey repo in its place.

**Comment by JedMeister** [comment]
No worries John. We are trying to get everything done by the end of the month as Alon will be away for a few weeks which will put a stop to any new appliances being published. So ideally if it's ready by then that'd be best. However, no pressure from me. Worst case, if it takes longer than you expect, we can deal with that. IMO better to delay a week or 2 and have it working right, than push it out prematurely. 

On the flip side, from here on in, we are hoping to do releases more often. We won't need to keep all the app versions in sync, so updating a single appliance will be an option. My suggestion for v14.2 is to fix any bugs you find (or at least document them if they appear quite edge case). But leave features to a minimum as we can take a bit more time with them and rebuild the appliance when it's ready.

Currently our releases are too slow and we're hoping this change in version regime will help. We're also hopeful that it will be conducive to further input from community members (having your pull requests sit there for ages and even after merge, still not become new appliances must really suck!)

This has been somewhat discussed publicly (here on GH and probably mentioned on the forums too) but I haven't yet "announced" it. I plan on doing that once 14.2 has been finalised.

**Comment by Dude4Linux** [comment]
Closing this PR. Will open new one against TurnKey repo.

**Pull request closed without merging**
